services:
  db:
      container_name: '${APP_NAME}-db'
      image: postgres
      restart: always
      environment:
          POSTGRES_USER: ${DB_USER}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
          POSTGRES_DB: ${DB_NAME}
      volumes:
          - ./data/:/var/lib/postgresql/data/
      ports:
          - "${DB_PORT}:5432"
  webserver:
      depends_on:
          - db  
      build: ./Docker/django
      container_name: servidorweb
      restart: always
      ports:
          - 8000:8000
      environment:
          POSTGRES_DB: ${DB_NAME}
          POSTGRES_USER: ${DB_USER}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
          POSTGRES_HOST: '${APP_NAME}-db'
          POSTGRES_PORT: ${DB_PORT}
      volumes:
          - ./back:/usr/src/app
  client:
      container_name: client
      build: ./Docker/react
      restart: always
      volumes:
          - ./front:/app
          - /app/node_modules
      ports:
          - '5173:5173'
