# Generated by Django 4.0.8 on 2023-04-24 17:29

from django.db import migrations, models
import games.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desarrollador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Idiomas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plataformas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='posts/default.png', upload_to=games.models.upload_to, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Juegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_portada', models.ImageField(null=True, upload_to='media/')),
                ('nombre', models.CharField(max_length=500)),
                ('descripcion', models.TextField()),
                ('publicacion', models.DateField(verbose_name='Fecha lanzamiento')),
                ('num_llaves', models.IntegerField()),
                ('publicado', models.DateField(null=True, verbose_name='Publicacion de la venta')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('desarrollador', models.ManyToManyField(to='games.desarrollador')),
                ('genero', models.ManyToManyField(to='games.genero')),
                ('idiomas', models.ManyToManyField(to='games.idiomas')),
                ('plataformas', models.ManyToManyField(to='games.plataformas')),
            ],
        ),
    ]
